### ISSUE TITLE
QueryReads "IndexError: list index out of range"

### ISSUE THREAD

**Issue by rahvis** [gersteinlab/SAMChain#4]
As per Readme.md file, queryRead.py is not working. 
Input .bam file: **mapt.NA12156.altex.bam**

[root@user-10 SAMChain]# python queryReads.py human **chr1:135654542-150631832** -dr bc -ref hg19.fa
{"method":"liststreamkeyitems","params":["metaData","chainInfo"],"id":"23756668-1589653078","chain_name":"human"}

**Traceback (most recent call last):
  File "queryReads.py", line 318, in <module>
    main()
  File "queryReads.py", line 299, in main
    readLength = chainInfo[0]["data"]["json"]["readLength"]
IndexError: list index out of range**

[root@dell-10 SAMChain]# python queryReads.py human **chr1:135654542** -dr bc -ref hg19.fa
{"method":"liststreamkeyitems","params":["metaData","chainInfo"],"id":"54403882-1589653043","chain_name":"human"}

**Traceback (most recent call last):
  File "queryReads.py", line 318, in <module>
    main()
  File "queryReads.py", line 299, in main
    readLength = chainInfo[0]["data"]["json"]["readLength"]
IndexError: list index out of range**

[root@dell-10 SAMChain]# python queryReads.py human **chr1:135654542 -dr bc -ref GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta**
{"method":"liststreamkeyitems","params":["metaData","chainInfo"],"id":"98800870-1589653568","chain_name":"human"}

Traceback (most recent call last):
  **File "queryReads.py", line 318, in <module>
    main()
  File "queryReads.py", line 299, in main
    readLength = chainInfo[0]["data"]["json"]["readLength"]
IndexError: list index out of range**

[root@user-10 SAMChain]# md5sum hg19.fa
530d89d3ef07fdb2a9b3c701fb4ca486  hg19.fa

[root@user-10 SAMChain]# python buildChain.py mapt.NA12156.altex.bam -cn human -dr bc
--CHAIN CREATION--
Created chain

MultiChain 1.0.9 Daemon (latest protocol 10012)

Starting up node...

Looking for genesis block...
Genesis block found

Other nodes can connect to this node using:
**multichaind human@xxx.xxx.xxx.xxx:6809**

This host has multiple IP addresses, so from some networks:
multichaind human@192.168.122.1:6809

Listening for API requests on port 6808 (local only - see rpcallowip setting)

Node ready.

--STREAM CREATION--
--PREPROCESSING--
--INSERTING DATA--
Chain construction complete! Chain name: human

 Total memory in bytes:

14921728

![bam_file](https://user-images.githubusercontent.com/64368687/82127440-2270d380-97d1-11ea-813d-33d891b84d3d.png)

**Comment by charlottebrannon** [comment]
Thanks for raising this issue–can you print the first few lines of your input bam file?

**Comment by rahvis** [comment]
Hi Charlotte, 

I am attaching the .bam files I used. 
i) a_out.bam (synthetic BAM file created using bam.py file attached)
ii) mapt.NA12156.altex.bam (downloaded from https://www.ncbi.nlm.nih.gov/tools/gbench/tutorial6/)

[mapt.NA12156.zip](https://github.com/gersteinlab/SAMChain/files/4639307/mapt.NA12156.zip)
[a_out.zip](https://github.com/gersteinlab/SAMChain/files/4639301/a_out.zip)

Thanks,
Rahul

**Synthetic .bam file**
import pysam 
header = { 'HD': {'VN': '1.0'},
            'SQ': [{'LN': 1575, 'SN': 'chr1'},
                   {'LN': 1584, 'SN': 'chr2'}] }

tmpfilename = 'a_out.bam'

with pysam.AlignmentFile(tmpfilename, "wb", header=header) as outf:
    a = pysam.AlignedSegment()
    a.query_name = "read_28833_29006_6945"
    a.query_sequence="AGCTTAGCTAGCTACCTATATCTTGGTCTTGGCCG"
    a.flag = 99
    a.reference_id = 0
    a.reference_start = 32
    a.mapping_quality = 20
    a.cigar = ((0,10), (2,1), (0,25))
    a.next_reference_id = 0
    a.next_reference_start=199
    a.template_length=167
    a.query_qualities = pysam.qualitystring_to_array("<<<<<<<<<<<<<<<<<<<<<:<9/,&,22;;<<<")
    a.tags = (("NM", 1),
              ("RG", "L1"))
    outf.write(a_out.bam)

**Comment by rahvis** [comment]
Can you please share the .bam file you have used? I can give it a try.

**Comment by charlottebrannon** [comment]
Here is one of the .bam files we used: https://www.encodeproject.org/files/ENCFF010ZDG/

**Comment by charlottebrannon** [comment]
Also, mapt.NA12156.altex.bam seems to be all contigs. SAMChain is designed to work for human chromosomes chr1-chry. One could alter the python scripts to change this if desired. This is clearly not the primary source of your issue, since you got the same error with the encode bam file given above, but thought I would mention.
