### ISSUE TITLE
No module named PrintSequence: buildBAM.py

### ISSUE THREAD

**Issue by rahvis** [gersteinlab/SAMChain#5]
Not able to find any module name - "PrintSequence" on PyPi 
We need not import "PrintSequence" in buildBAM.py as its not being used anywhere in the file. 
I also do not find this module  in PyPi or even on Google (does not exist).

Is this the issue with the code? I was able to successfully store mapt.NA12156.altex.bam in Blockchain (multichain), but generating a .bam file does not work. 

**Most of the scripts are giving error message "IndexError: list index out of range**".

[root@user-10 SAMChain]# python buildBAM.py human -dr bc -bam new.bam -ref hg19.fa
Traceback (most recent call last):
  File "buildBAM.py", line 23, in <module>
    import PrintSequence
**ImportError: No module named PrintSequence**

**If I comment out #PrintSequence in buildBAM.py, we get this error message:** 

[root@user-10 SAMChain]# python buildBAM.py human -dr bc -bam new.bam -ref hg19.fa
['multichain-cli', 'human', '-datadir=bc', 'liststreamkeyitems', 'metaData', 'chainInfo', 'false', '100000000']
**Traceback (most recent call last):
  File "buildBAM.py", line 472, in <module>
    main()
  File "buildBAM.py", line 324, in main
    **readLength = chainInfo[0]["data"]["json"]["readLength"]**
IndexError: list index out of range**

**Comment by charlottebrannon** [comment]
Hi Rahul–thanks for pointing this out. This is an artifact from a previous version of the code. We have removed the PrintSequence import from buildBAM.py, along with a few unnecessary print statements. But these should not be the cause of the other issues.
