### ISSUE TITLE
BAM file used for experiments 

### ISSUE THREAD

**Issue by rahvis** [gersteinlab/SAMChain#6]
**Can you please provide the input .bam file and the reference file used to create README.md?**
This can help reproduce the experiment. 
I am using Python 2.7 on Red Hat 7.5 x86_64

**Comment by rahvis** [comment]
https://www.encodeproject.org/files/ENCFF010ZDG/

**Comment by dc4818773** [comment]
Hi Rahul,

I'm sorry to bother you, but I've been getting a flood of these emails from
SAMchain every time you make a modification or do anything with SAMchain.
I've been getting these emails for several days now. Would it be possible
to disable the email notices or remove my email addr from the SAMchain
mailing list?

Many thanks, and apologies for any inconvenience.
