### ISSUE TITLE
queryReads.py and buildBAM.py  not working with ENCFF010ZDG.bam

### ISSUE THREAD

**Issue by rahvis** [gersteinlab/SAMChain#8]
The issue remains the same even if I use the .bam file you suggested - "ENCFF010ZDG.bam".

[root@user-10 SAMChain]# **python buildChain.py ENCFF010ZDG.bam -cn enc -dr bc**
--CHAIN CREATION--
Created chain

MultiChain 1.0.9 Daemon (latest protocol 10012)

Starting up node...

Looking for genesis block...
Genesis block found

Other nodes can connect to this node using:
multichaind enc@10.230.161.185:6733

This host has multiple IP addresses, so from some networks:
multichaind enc@192.168.122.1:6733

Listening for API requests on port 6732 (local only - see rpcallowip setting)

**Node ready.

--STREAM CREATION--
--PREPROCESSING--
--INSERTING DATA--
Chain construction complete! Chain name: enc

 Total memory in bytes:

14925824**

[root@user-10 SAMChain]# **python queryReads.py enc chr1:1880913 -dr bc -ref GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta**
{"method":"liststreamkeyitems","params":["metaData","chainInfo"],"id":"92758465-1589709457","chain_name":"enc"}

Traceback (most recent call last):
  File "queryReads.py", line 317, in <module>
    main()
  File "queryReads.py", line 298, in main
    readLength = chainInfo[0]["data"]["json"]["readLength"]
**IndexError: list index out of range**

[root@user-10 SAMChain]# **python buildBAM.py enc -dr bc -bam output.bam -ref GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta**
['multichain-cli', 'enc', '-datadir=bc', 'liststreamkeyitems', 'metaData', 'chainInfo', 'false', '100000000']
Traceback (most recent call last):
  File "buildBAM.py", line 472, in <module>
    main()
  File "buildBAM.py", line 324, in main
    readLength = chainInfo[0]["data"]["json"]["readLength"]
**IndexError: list index out of range**

[root@user-10 SAMChain]# **ls -ltr bc/enc/**
total 2084
-rw-r--r-- 1 root root   8473 May 17 05:47 params.dat.bak
-rw-r--r-- 1 root root     79 May 17 05:47 multichain.conf
drwxr-xr-x 2 root root     85 May 17 05:47 permissions.db
-rw------- 1 root root      5 May 17 05:47 multichain.pid
-rw------- 1 root root      0 May 17 05:47 db.log
drwx------ 2 root root     28 May 17 05:47 database
-rw------- 1 root root   8705 May 17 05:48 params.dat
drwx------ 2 root root     85 May 17 05:48 entities.db
drwx------ 2 root root     85 May 17 05:48 chainstate
drwx------ 3 root root     59 May 17 05:48 blocks
-rw------- 1 root root  16384 May 17 05:48 wallet.dat
-rw------- 1 root root 307072 May 17 05:56 permissions.dat
-rw-r--r-- 1 root root 638433 May 17 05:56 permissions.log
-rw------- 1 root root 111264 May 17 05:56 entities.dat
drwx------ 3 root root   4096 May 17 05:56 wallet
-rw------- 1 root root 255187 May 17 05:56 debug.log

[root@user-10 SAMChain]# ls -ltr bc/enc/blocks/
total 17408
drwx------ 2 root root       85 May 17 05:48 index
-rw------- 1 root root 16777216 May 17 05:56 blk00000.dat
-rw------- 1 root root  1048576 May 17 05:56 rev00000.dat

**Comment by charlottebrannon** [comment]
Below are the exact commands and outputs we get when using the scripts in this repository. 
```
cmb@idrac-ub:~/multichain-project$ uname -a
Linux idrac-ub 5.0.0-37-generic #40-Ubuntu SMP Thu Nov 14 00:14:01 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

cmb@idrac-ub:~/multichain-project$ python --version
Python 2.7.16

cmb@idrac-ub:~/multichain-project/github-test$ git clone https://github.com/gersteinlab/SAMChain
Cloning into 'SAMChain'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 17 (delta 3), reused 2 (delta 0), pack-reused 0
Unpacking objects: 100% (17/17), done.


cmb@idrac-ub:~/multichain-project/github-test/SAMChain$ python buildChain.py ../ENCFF010ZDG_1hundred.bam -cn cmbchain -dr ../chains
--CHAIN CREATION--
Created chain

MultiChain 2.0.3 Daemon (Community Edition, latest protocol 20011)

Starting up node...

Looking for genesis block...
Genesis block found

Other nodes can connect to this node using:
multichaind cmbchain@128.36.196.88:2905

This host has multiple IP addresses, so from some networks:
multichaind cmbchain@192.168.122.222:2905

Listening for API requests on port 2904 (local only - see rpcallowip setting)

Node ready.

--STREAM CREATION--
--PREPROCESSING--
--INSERTING DATA--
Chain construction complete! Chain name: cmbchain


 Total memory in bytes:


19816448


python queryReads.py cmbchain chr8:132013227 -dr ../chains -ref ../GRCh38_no_alt_analysis_set_GCA_000001405.15.fa
{"method":"liststreamkeyitems","params":["metaData","chainInfo"],"id":"74177645-1589716118","chain_name":"cmbchain"}

{"method":"liststreamkeys","params":["chr8stream14"],"id":"74177645-1589716118","chain_name":"cmbchain"}

{"method":"liststreamkeyitems","params":["chr8stream14","readID=FC30V1RHM_20081223:8:45:1237:746"],"id":"74177645-1589716118","chain_name":"cmbchain"}

{"method":"liststreamkeyitems","params":["allReadData","FC30V1RHM_20081223:8:45:1237:746"],"id":"74177645-1589716118","chain_name":"cmbchain"}

FC30V1RHM_20081223:8:45:1237:746	0	chr8	132013227	37	28M	-1	0	0	TTTCTTTCATGACATTGGTTAACATTTA	<<<<<<<<<<<<<<<<<<<<<<<<<<<<	X0:1	X1:0	MD:28	PG:MarkDuplicates	XG:0	NM:0	XM:0	XO:0	XT:U

cmb@idrac-ub:~/multichain-project/github-test/SAMChain$ python buildBAM.py cmbchain -dr ../chains -bam cmb.bam -ref ../GRCh38_no_alt_analysis_set_GCA_000001405.15.fa
['multichain-cli', 'cmbchain', '-datadir=../chains', 'liststreamkeyitems', 'metaData', 'chainInfo', 'false', '100000000']
['multichain-cli', 'cmbchain', '-datadir=../chains', 'liststreamkeyitems', 'metaData', 'header', 'false', '1000000000']


 Total memory in bytes:


68427776


cmb@idrac-ub:~/multichain-project/github-test/SAMChain$ samtools view cmb.bam | head
FC30V1RHM_20081223:8:56:237:918	0	chr1	25668311	37	28M	*	1	0	ATTCAGAATTCTCCTGCTGGCTGCTGGC	<<<<<<<<<<<<<<<<<<<<<<<<<<<<	X0:Z:1	X1:Z:0	MD:Z:28	PG:Z:MarkDuplicates	XG:Z:0	NM:Z:0	XM:Z:0	XO:Z:0	XT:Z:U
FC30V1RHM_20081223:8:56:237:918	0	chr1	25668311	37	28M	*	1	0	ATTCAGAATTCTCCTGCTGGCTGCTGGC	<<<<<<<<<<<<<<<<<<<<<<<<<<<<	X0:Z:1	X1:Z:0	MD:Z:28	PG:Z:MarkDuplicates	XG:Z:0	NM:Z:0	XM:Z:0	XO:Z:0	XT:Z:U
FC30V1RHM_20081223:8:67:228:1124	16	chr1	37256705	37	28M	*	1	0	ACTCCCTCCCTGCTCCCATCCTCCTTCT	<<<<<<<<<<<<<<<<<<<<<<<<<<<<	X0:Z:1	X1:Z:0	MD:Z:28	PG:Z:MarkDuplicates	XG:Z:0	NM:Z:0	XM:Z:0	XO:Z:0	XT:Z:U
FC30V1RHM_20081223:8:6:1727:448	0	chr1	41726411	37	28M	*	1	0	GAAGCTGTTACAGATTTTGTAGATGTTT	<<<<<<<<<<<<<<<<<<<<<<<<<<<<	X0:Z:1	X1:Z:0	MD:Z:28	PG:Z:MarkDuplicates	XG:Z:0	NM:Z:0	XM:Z:0	XO:Z:0	XT:Z:U
	
```
(using downsampled version of the bam to speed up tests)
